config/routes.rb
Rails.application.routes.draw do
  root to: 'fruits#index'
  resources :fruits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: [:show, :edit, :update, :destroy]

  # GET /fruits
  # GET /fruits.json
  def index
    @fruits = Fruit.all
  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to @fruit, notice: 'Fruit was successfully created.' }
        format.json { render :show, status: :created, location: @fruit }
      else
        format.html { render :new }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1
  # PATCH/PUT /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to @fruit, notice: 'Fruit was successfully updated.' }
        format.json { render :show, status: :ok, location: @fruit }
      else
        format.html { render :edit }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      format.html { redirect_to fruits_url, notice: 'Fruit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fruit_params
      params.require(:fruit).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/views/fruits/_form.html.haml
= form_with(model: fruit, local: true) do |form|
  - if fruit.errors.any?
    #error_explanation
      %h2
        = pluralize(fruit.errors.count, "error")
        prohibited this fruit from being saved:
      %ul
        - fruit.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :image
    = form.text_field :image
  .actions
    = form.submit

app/views/fruits/edit.html.haml
%h1 Editing Fruit
= render 'form', fruit: @fruit
= link_to 'Show', @fruit
|
= link_to 'Back', fruits_path

app/views/fruits/index.html.haml
%nav.navbar.navbar-expand-sm.sticky-top.navbar-light{style: "background-color: #BAD3FF"}
  %a.navbar-brand{href: root_path} Furtweet
  %button.navbar-toggler{"aria-controls": "navbar", "aria-expanded": "false", "aria-label": "Toggle navigation", "data-target": "#navbar", "data-toggle": "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navbar.collapse.navbar-collapse.justify-content-end
    %ul.navbar-nav.mr-auto
      %li.nav-item.dropdown
        %a#dropdown.nav-link.dropdown-toggle{"aria-expanded": "false", "aria-haspopup": "true", "data-toggle": "dropdown", href: "#"} ドロップダウン
        .dropdown-menu{"aria-labelledby": "dropdown"}
          %a.dropdown-item{href: "#"} リンク1
          %a.dropdown-item{href: "#"} リンク2
          %a.dropdown-item{href: "#"} リンク3
    %form.form-inline.my-2.my-md-0
      %input.form-control.mr-sm-1{placeholder: "Search", type: "search"}
      %button.btn.btn-outline-info.mt-2.my-sm-0{type: "submit"} Search

app/views/fruits/new.html.haml
%h1 New Fruit
= render 'form', fruit: @fruit
= link_to 'Back', fruits_path

app/views/fruits/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @fruit.name
%p
  %strong Image:
  = @fruit.image
= link_to 'Edit', edit_fruit_path(@fruit)
|
= link_to 'Back', fruits_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Frutweet
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield